### ISSUE TITLE
`machine-controller-manager-provider-local node` image build fails

### ISSUE THREAD

**Issue by shafeeqes** [gardener/machine-controller-manager-provider-local#9]
**What happened**:
`machine-controller-manager-provider-local node` image build fails with:
```
#10 [linux/amd64 2/9] RUN apt-get update -yq &&     apt-get install -yq --no-install-recommends wget apparmor apparmor-utils jq
#0 0.193 Ign:1 http://security.ubuntu.com/ubuntu impish-security InRelease
#0 0.210 Err:2 http://security.ubuntu.com/ubuntu impish-security Release
#0 0.210   404  Not Found [IP: 91.189.91.39 80]
#0 0.318 Ign:3 http://archive.ubuntu.com/ubuntu impish InRelease
#0 0.396 Ign:4 http://archive.ubuntu.com/ubuntu impish-updates InRelease
...
#0 0.711 Err:8 http://archive.ubuntu.com/ubuntu impish-backports Release
#0 0.712   404  Not Found [IP: 185.125.190.39 80]
#0 0.719 Reading package lists...
#0 0.725 E: The repository 'http://security.ubuntu.com/ubuntu impish-security Release' does not have a Release file.
#0 0.726 E: The repository 'http://archive.ubuntu.com/ubuntu impish Release' does not have a Release file.
#0 0.728 E: The repository 'http://archive.ubuntu.com/ubuntu impish-updates Release' does not have a Release file.
#0 0.728 E: The repository 'http://archive.ubuntu.com/ubuntu impish-backports Release' does not have a Release file.
#10 ERROR: process "/bin/sh -c apt-get update -yq &&     apt-get install -yq --no-install-recommends wget apparmor apparmor-utils jq" did not complete successfully: exit code: 100
------
```
[Ref](https://github.com/gardener/machine-controller-manager-provider-local/runs/8221455316?check_suite_focus=true#step:7:201) 
This is due to https://github.com/kubernetes-sigs/kind/issues/2863, and it is fixed in the `kindest/node:v1.25.0` image but we cannot use this yet because of https://github.com/gardener/gardener/issues/5325

**What you expected to happen**:
Node image build to be successful.

**How to reproduce it (as minimally and precisely as possible)**:
Run `docker build -t test:v1 ./node/.` locally with the current kind image (https://github.com/gardener/machine-controller-manager-provider-local/blob/c85c4eaf942d87fa1cb694d6df79016c5ffe28e2/node/Dockerfile#L1).
and see it fail on step: 
https://github.com/gardener/machine-controller-manager-provider-local/blob/c85c4eaf942d87fa1cb694d6df79016c5ffe28e2/node/Dockerfile#L6-L7
with the above error.

Run again with `kindest/node:v1.25.0` and see it passes.
**Anything else we need to know**:

**Environment**:

**Comment by oliver-goetz** [comment]
This is fixed meanwhile.
